
[tcp]
  [tcp.t1]
  from = "localhost:9001"
  to = "localhost:9002"

[udp]
  [udp.u1]
  from = "localhost:9101"
  to = "localhost:9102"

[http]
  [http.h1]
  listen = "localhost:9201"
    [[http.h1.basic_auth]]
    user = "user1"
    password = "password1"
    [[http.h1.basic_auth]]
    # can give password without user (user can be anything)
    password = "password2"

  [http.h2]
  listen = "localhost:9202"
  basic_auth = [
        { password = "password3" }
  ]

[https]
  [https.h1]
  listen = "localhost:9301"
  cert = "./server.crt"
  key = "./server.key"
  basic_auth = [
        { user = "u1", password = "123456" }
  ]
